# Limpieza de los .csv

In [10]:
# Importamos todas las librerias necesarias para hacer la limpieza
import pandas as pd

## PIB_INE

In [11]:
# Cargamos los datos
df_pib = pd.read_csv('../../data/ine/pib_ine_latest.csv')
df_pib.head()

,Indicador,Periodo,Valor,Variacion_interanual_%
0,3.1.6. Marmol,2008,3751205.0,NaN
1,M.2.2.3. Plomo (contenido de metal),2008,0.0,NaN
2,2.2.4. Zinc,2008,0.0,NaN
3,M.2.2.4. Zinc (contenido de metal),2008,0.0,NaN
4,2.2.5. Estaño,2008,27572.0,-99.264983

#### PASO 1. Inspección y filtrado
1. Comprobamos los indicadores que hay para saber cuales filtrar

In [12]:
df_pib["Indicador"].unique()

array(['3.1.6. Marmol', 'M.2.2.3.  Plomo (contenido de metal)',
       '2.2.4.  Zinc', 'M.2.2.4.  Zinc (contenido de metal)',
       '2.2.5.  Estaño', 'M.2.2.5.  Estaño (contenido de metal)',
       '2.2.6.  Minerales de oro, plata y metales preciosos',
       'M.2.2.6.  Minerales de oro, plata y metales preciosos (contenido de metal)',
       '2.2.7.  Minerales de bauxita y otros minerales de aluminio',
       'M.2.2.7.  Minerales de bauxita y otros minerales de aluminio (contenido de metal)',
       '2.2.8.  Minerales de uranio y torio', '2.2.3.  Plomo',
       'M.2.2.8.  Minerales de uranio y torio (contenido de metal)',
       'M.2.2.9.  Otros minerales metálicos (contenido de metal)',
       '3.  Minerales no metálicos',
       '3.1. Piedras de construcción u ornamentales (excl. Pizarra)',
       '3.1.1. Arenisca', '3.1.2. Basalto', '3.1.3. Fonolita',
       '3.1.4. Granito', '3.1.5. Margas', '3.1.7. Ofita',
       '3.1.8. Pórfidos', '2.2.9.  Otros minerales metálicos',
       'M.2.2.2.  Níquel (contenido de metal)', '2.2.2.  Níquel',
       'M.2.2.1.  Cobre (contenido de metal)',
       '1.1.6.  Cultivos oleaginosos', '1.1.7.  Hortalizas',
       '1.1.8.  Frutas', '1.1.9.  Fibras', '1.1.10. Otros cultivos',
       '1.2.  Residuos de cultivos usados, cultivos forrajeros y biomasa pastada',
       '1.2.1.  Residuos de cultivos usados', '1.2.1.1.  Paja',
       '1.2.1.2.  Otros residuos de cultivos',
       '1.2.2.  Cultivos forrajeros y biomasa pastada',
       '1.2.2.1.  Cultivos forrajeros', '1.2.2.2.  Biomasa pastada',
       '1.3.  Madera', '1.3.1.  Madera en bruto',
       '1.3.2.  Leña y otras extracciones',
       '1.4.  Captura de peces, plantas/animales acuáticos, caza y recolección',
       '1.4.1.  Peces capturados',
       '1.4.2.  Resto de animales y plantas acuáticos',
       '1.4.3.  Caza y recolección',
       '2.  Minerales metálicos (mineral en bruto)',
       '2.1.  Minerales de hierro',
       '2.2.  Minerales metálicos no férreos', '2.2.1.  Cobre',
       '3.1.9. Serpentina y dunita', '1.1.5.  Frutos secos',
       '3.1.10. Otras', '3.2.1. Creta', '3.8.1. Arenas y grava',
       '3.8.2. Sílice y arenas silíceas', '3.9. Otros minerales',
       '3.9.1. Cuarcita', '3.9.2. Cuarzo', '3.9.3. Esteatita',
       '3.9.4. Feldespato', '3.9.5. Glauberita', '3.9.6. Magnesita',
       '3.9.7. Mica', '3.8. Arenas y grava', '3.9.8. Piedra pómez',
       '3.9.10. Trípoli', '3.9.11. Otros', '4.  Combustibles fósiles',
       '4.1.  Carbón y otros recursos energéticos sólidos',
       '4.1.1.  Lignito', '4.1.2.  Hulla y antracita',
       '4.1.3.  Arenas de alquitrán y pizarras bituminosas',
       '4.1.4.  Turba', '4.2.  Recursos energéticos líquidos y gaseosos',
       '4.2.1.  Crudos de petróleo y gas natural licuado',
       '3.9.9. Thenardita', '3.7.7. Arcillas comunes', '3.7.6. Sepiolita',
       '3.7.5. Caolín lavado', '3.2.2. Dolomía', '3.3. Pizarra',
       '3.4. Minerales para fertilizantes y químicos', '3.4.1. Baritina',
       '3.4.2. Cloruro potásico', '3.4.3. Espato-f ácido',
       '3.4.4. Espato-f metalúrgico', '3.4.5. Espato-fluor cerámico',
       '3.4.6. Oxidos de hierro', '3.4.7. Pirita',
       '3.4.8. Sales potásicas', '3.5. Sal', '3.5.1. Sal gema',
       '3.5.2. Sal manantial', '3.5.3. Sal marina',
       '3.6. Piedra caliza y yeso', '3.6.1. Piedra caliza', '3.6.2. Yeso',
       '3.7. Arcillas y caolín', '3.7.1. Arcilla refractaria',
       '3.7.2. Attapulgita', '3.7.3. Bentonita', '3.7.4. Caolín bruto',
       '3.2. Creta y dolomía', '1.1.4.  Leguminosas',
       '4.2.2.  Gas natural', '1.1.1.  Cereales', 'EXTRACCION NACIONAL',
       '1.1.  Cultivos primarios', '1.1.2.  Raices y tubérculos',
       '1.  Biomasa', '1.1.3.  Cultivos azucareros'], dtype=object)

2. Filtrar solo el PIB Total

In [13]:
df_pib_clean = df_pib[df_pib['Indicador'].str.contains("Producto interior bruto", case=False, na=False)].copy()

In [14]:
df_pib_clean.head()

Empty DataFrame
Columns: [Indicador, Periodo, Valor, Variacion_interanual_%]
Index: []

EXTRACCION NACIONAL